<img src="https://s3-sa-east-1.amazonaws.com/preditiva.ai/diversos/preditiva_assinatura.jpg">

# Regressão Logística

## Demonstração

### Definição da base de dados

In [1]:
import numpy as np

x = [0,1,2,3,5,6,7,8]


In [3]:
x = np.reshape(x, (8,1))
x

array([[0],
       [1],
       [2],
       [3],
       [5],
       [6],
       [7],
       [8]])

In [4]:


y = [0,0,0,0,1,1,1,1]

y = np.reshape(y, (8,1))

In [5]:
y

array([[0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1]])

### Ajuste de uma regressão logística usando o Scikit Learn

In [6]:
from sklearn.linear_model import LogisticRegression



In [13]:
# Define estrutura e configurações do modelo
modelo = LogisticRegression(random_state=0,
                            fit_intercept=True) # modelo dá uma estimativa para beta 0

# Ajusta o modelo
modelo.fit(x, y.ravel())

LogisticRegression(random_state=0)

In [14]:
# Obtenção dos coeficientes do modelo
print('Intercepto: {}' .format(modelo.intercept_))
print('Coeficientes: {}' .format(modelo.coef_))

Intercepto: [-4.54460456]
Coeficientes: [[1.13614635]]


### Cálculo do score z

In [15]:
x

array([[0],
       [1],
       [2],
       [3],
       [5],
       [6],
       [7],
       [8]])

In [16]:
# Calculando z
z = -4.54460456+1.13614635*x

np.round(z, decimals=4)

array([[-4.5446],
       [-3.4085],
       [-2.2723],
       [-1.1362],
       [ 1.1361],
       [ 2.2723],
       [ 3.4084],
       [ 4.5446]])

### Cálculo da probabilidade de Y = 1

In [17]:
# Calculando a probabilidade de y=1 ou g(z) manualmente
gz = 1/(1+np.exp(-z))
np.round(gz, decimals=4)

array([[0.0105],
       [0.032 ],
       [0.0934],
       [0.243 ],
       [0.757 ],
       [0.9066],
       [0.968 ],
       [0.9895]])

In [18]:
# Calculando a probabilidade utilizando os métodos do Scikit-Learn
modelo.predict_proba(x)

array([[0.98948732, 0.01051268],
       [0.96796783, 0.03203217],
       [0.90655781, 0.09344219],
       [0.75697493, 0.24302507],
       [0.24303212, 0.75696788],
       [0.09344544, 0.90655456],
       [0.03203336, 0.96796664],
       [0.01051308, 0.98948692]])

### Cálculo do y estimado

In [19]:
# calculando o y estimado manualmente
y_estimado = np.where(gz >= 0.5 , 1 , 0)
y_estimado

array([[0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1]])

In [20]:
# Calculando o y estimado utilizando os métodos do Scikit-Learn
modelo.predict(x)

array([0, 0, 0, 0, 1, 1, 1, 1])

### Cálculo da Acurácia

In [22]:
(y_estimado == y).sum()

8

In [23]:
len(y)

8

In [24]:
# calculando a acurácia manualmente
acuracia = (y_estimado == y).sum() / len(y)
acuracia

1.0

In [25]:
# calculando a acurácia utilizando os métodos do Scikit-Learn
from sklearn.metrics import accuracy_score

accuracy_score(y_estimado, y)

1.0